import Head from "next/head";
import { DUMMY_EVENTS } from "../../dummy-data";
import EventList from "../../components/events/EventList";
import { getFeaturedEvents, getAllEvents } from "../../helpers/api-utils";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <EventList events={props.featuredEvents} />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const featuredEvents = await getFeaturedEvents();
  

  return {
    props: {
      featuredEvents: featuredEvents
    },
    revalidate : 1800
  }
}
