import Head from 'next/head'
import Link from "next/link";
import { DUMMY_EVENTS } from "../../dummy-data";
import EventList from "../../components/events/EventList";

export default function Home() {
 
  const getFeaturedEvents = () => {
    console.log(DUMMY_EVENTS)
    return DUMMY_EVENTS.filter((event) => event.isFeatured);
  }
  const featuredEvents = getFeaturedEvents()
  console.log(featuredEvents);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>        
        <EventList featuredEvents={featuredEvents} />
      </div>
    </>
  );
}
